---
name: hybridesmbench
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.11
  - esmvalcore
  - esmvaltool-python
  - iris
  - ncdata
  - xarray

  # develop
  - ipykernel
  - pre-commit
